<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class GenresSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
        $genres = [
            ['id' => 1, 'name' => 'Action', 'slug' => 'action', 'type' => 'genres'],
            ['id' => 2, 'name' => 'Adventure', 'slug' => 'adventure', 'type' => 'genres'],
            ['id' => 3, 'name' => 'Avant Garde', 'slug' => 'avant-garde', 'type' => 'genres'],
            ['id' => 4, 'name' => 'Award Winning', 'slug' => 'award-winning', 'type' => 'genres'],
            ['id' => 5, 'name' => 'Boys Love', 'slug' => 'boys-love', 'type' => 'genres'],
            ['id' => 6, 'name' => 'Comedy', 'slug' => 'comedy', 'type' => 'genres'],
            ['id' => 7, 'name' => 'Drama', 'slug' => 'drama', 'type' => 'genres'],
            ['id' => 8, 'name' => 'Fantasy', 'slug' => 'fantasy', 'type' => 'genres'],
            ['id' => 9, 'name' => 'Girls Love', 'slug' => 'girls-love', 'type' => 'genres'],
            ['id' => 10, 'name' => 'Gourmet', 'slug' => 'gourmet', 'type' => 'genres'],
            ['id' => 11, 'name' => 'Horror', 'slug' => 'horror', 'type' => 'genres'],
            ['id' => 12, 'name' => 'Mystery', 'slug' => 'mystery', 'type' => 'genres'],
            ['id' => 13, 'name' => 'Romance', 'slug' => 'romance', 'type' => 'genres'],
            ['id' => 14, 'name' => 'Sci-Fi', 'slug' => 'sci-fi', 'type' => 'genres'],
            ['id' => 15, 'name' => 'Slice of Life', 'slug' => 'slice-of-life', 'type' => 'genres'],
            ['id' => 16, 'name' => 'Sports', 'slug' => 'sports', 'type' => 'genres'],
            ['id' => 17, 'name' => 'Supernatural', 'slug' => 'supernatural', 'type' => 'genres'],
            ['id' => 18, 'name' => 'Suspense', 'slug' => 'suspense', 'type' => 'genres'],
            ['id' => 19, 'name' => 'Ecchi', 'slug' => 'ecchi', 'type' => 'explicit_genres'],
            ['id' => 20, 'name' => 'Erotica', 'slug' => 'erotica', 'type' => 'explicit_genres'],
            ['id' => 21, 'name' => 'Hentai', 'slug' => 'hentai', 'type' => 'explicit_genres'],
            ['id' => 22, 'name' => 'Adult Cast', 'slug' => 'adult-cast', 'type' => 'themes'],
            ['id' => 23, 'name' => 'Anthropomorphic', 'slug' => 'anthropomorphic', 'type' => 'themes'],
            ['id' => 24, 'name' => 'CGDCT', 'slug' => 'cgdct', 'type' => 'themes'],
            ['id' => 25, 'name' => 'Childcare', 'slug' => 'childcare', 'type' => 'themes'],
            ['id' => 26, 'name' => 'Combat Sports', 'slug' => 'combat-sports', 'type' => 'themes'],
            ['id' => 27, 'name' => 'Crossdressing', 'slug' => 'crossdressing', 'type' => 'themes'],
            ['id' => 28, 'name' => 'Delinquents', 'slug' => 'delinquents', 'type' => 'themes'],
            ['id' => 29, 'name' => 'Detective', 'slug' => 'detective', 'type' => 'themes'],
            ['id' => 30, 'name' => 'Educational', 'slug' => 'educational', 'type' => 'themes'],
            ['id' => 31, 'name' => 'Gag Humor', 'slug' => 'gag-humor', 'type' => 'themes'],
            ['id' => 32, 'name' => 'Gore', 'slug' => 'gore', 'type' => 'themes'],
            ['id' => 33, 'name' => 'Harem', 'slug' => 'harem', 'type' => 'themes'],
            ['id' => 34, 'name' => 'High Stakes Game', 'slug' => 'high-stakes-game', 'type' => 'themes'],
            ['id' => 35, 'name' => 'Historical', 'slug' => 'historical', 'type' => 'themes'],
            ['id' => 36, 'name' => 'Idols (Female)', 'slug' => 'idols-female', 'type' => 'themes'],
            ['id' => 37, 'name' => 'Idols (Male)', 'slug' => 'idols-male', 'type' => 'themes'],
            ['id' => 38, 'name' => 'Isekai', 'slug' => 'isekai', 'type' => 'themes'],
            ['id' => 39, 'name' => 'Iyashikei', 'slug' => 'iyashikei', 'type' => 'themes'],
            ['id' => 40, 'name' => 'Love Polygon', 'slug' => 'love-polygon', 'type' => 'themes'],
            ['id' => 41, 'name' => 'Magical Sex Shift', 'slug' => 'magical-sex-shift', 'type' => 'themes'],
            ['id' => 42, 'name' => 'Mahou Shoujo', 'slug' => 'mahou-shoujo', 'type' => 'themes'],
            ['id' => 43, 'name' => 'Martial Arts', 'slug' => 'martial-arts', 'type' => 'themes'],
            ['id' => 44, 'name' => 'Mecha', 'slug' => 'mecha', 'type' => 'themes'],
            ['id' => 45, 'name' => 'Medical', 'slug' => 'medical', 'type' => 'themes'],
            ['id' => 46, 'name' => 'Military', 'slug' => 'military', 'type' => 'themes'],
            ['id' => 47, 'name' => 'Music', 'slug' => 'music', 'type' => 'themes'],
            ['id' => 48, 'name' => 'Mythology', 'slug' => 'mythology', 'type' => 'themes'],
            ['id' => 49, 'name' => 'Organized Crime', 'slug' => 'organized-crime', 'type' => 'themes'],
            ['id' => 50, 'name' => 'Otaku Culture', 'slug' => 'otaku-culture', 'type' => 'themes'],
            ['id' => 51, 'name' => 'Parody', 'slug' => 'parody', 'type' => 'themes'],
            ['id' => 52, 'name' => 'Performing Arts', 'slug' => 'performing-arts', 'type' => 'themes'],
            ['id' => 53, 'name' => 'Pets', 'slug' => 'pets', 'type' => 'themes'],
            ['id' => 54, 'name' => 'Psychological', 'slug' => 'psychological', 'type' => 'themes'],
            ['id' => 55, 'name' => 'Racing', 'slug' => 'racing', 'type' => 'themes'],
            ['id' => 56, 'name' => 'Reincarnation', 'slug' => 'reincarnation', 'type' => 'themes'],
            ['id' => 57, 'name' => 'Reverse Harem', 'slug' => 'reverse-harem', 'type' => 'themes'],
            ['id' => 58, 'name' => 'Love Status Quo', 'slug' => 'love-status-quo', 'type' => 'themes'],
            ['id' => 59, 'name' => 'Samurai', 'slug' => 'samurai', 'type' => 'themes'],
            ['id' => 60, 'name' => 'School', 'slug' => 'school', 'type' => 'themes'],
            ['id' => 61, 'name' => 'Showbiz', 'slug' => 'showbiz', 'type' => 'themes'],
            ['id' => 62, 'name' => 'Space', 'slug' => 'space', 'type' => 'themes'],
            ['id' => 63, 'name' => 'Strategy Game', 'slug' => 'strategy-game', 'type' => 'themes'],
            ['id' => 64, 'name' => 'Super Power', 'slug' => 'super-power', 'type' => 'themes'],
            ['id' => 65, 'name' => 'Survival', 'slug' => 'survival', 'type' => 'themes'],
            ['id' => 66, 'name' => 'Team Sports', 'slug' => 'team-sports', 'type' => 'themes'],
            ['id' => 67, 'name' => 'Time Travel', 'slug' => 'time-travel', 'type' => 'themes'],
            ['id' => 68, 'name' => 'Vampire', 'slug' => 'vampire', 'type' => 'themes'],
            ['id' => 69, 'name' => 'Video Game', 'slug' => 'video-game', 'type' => 'themes'],
            ['id' => 70, 'name' => 'Visual Arts', 'slug' => 'visual-arts', 'type' => 'themes'],
            ['id' => 71, 'name' => 'Workplace', 'slug' => 'workplace', 'type' => 'themes'],
            ['id' => 72, 'name' => 'Urban Fantasy', 'slug' => 'urban-fantasy', 'type' => 'themes'],
            ['id' => 73, 'name' => 'Villainess', 'slug' => 'villainess', 'type' => 'themes'],
            ['id' => 74, 'name' => 'Josei', 'slug' => 'josei', 'type' => 'demographics'],
            ['id' => 75, 'name' => 'Kids', 'slug' => 'kids', 'type' => 'demographics'],
            ['id' => 76, 'name' => 'Seinen', 'slug' => 'seinen', 'type' => 'demographics'],
            ['id' => 77, 'name' => 'Shoujo', 'slug' => 'shoujo', 'type' => 'demographics'],
            ['id' => 78, 'name' => 'Shounen', 'slug' => 'shounen', 'type' => 'demographics'],
            ['id' => 79, 'name' => 'Other', 'slug' => 'other', 'type' => 'other']
        ];

        // Vietnamese translations mapping for all genres
        $vietnameseTranslations = [
            'Action' => 'Hành động',
            'Adventure' => 'Phiêu lưu',
            'Avant Garde' => 'Tiên phong',
            'Award Winning' => 'Đoạt giải',
            'Boys Love' => 'Tình yêu nam',
            'Comedy' => 'Hài hước',
            'Drama' => 'Chính kịch',
            'Fantasy' => 'Thần thoại',
            'Girls Love' => 'Tình yêu nữ',
            'Gourmet' => 'Ẩm thực',
            'Horror' => 'Kinh dị',
            'Mystery' => 'Bí ẩn',
            'Romance' => 'Lãng mạn',
            'Sci-Fi' => 'Khoa học viễn tưởng',
            'Slice of Life' => 'Đời thường',
            'Sports' => 'Thể thao',
            'Supernatural' => 'Siêu nhiên',
            'Suspense' => 'Giật gân',
            'Ecchi' => 'Ecchi',
            'Erotica' => 'Khiêu dâm',
            'Hentai' => 'Hentai',
            'Adult Cast' => 'Nhân vật người lớn',
            'Anthropomorphic' => 'Nhân hình hóa',
            'CGDCT' => 'CGDCT (Cute Girls Doing Cute Things)',
            'Childcare' => 'Chăm sóc trẻ em',
            'Combat Sports' => 'Thể thao chiến đấu',
            'Crossdressing' => 'Crossdressing',
            'Delinquents' => 'Delinquent',
            'Detective' => 'Thám tử',
            'Educational' => 'Giáo dục',
            'Gag Humor' => 'Hài kịch',
            'Gore' => 'Bạo lực máu me',
            'Harem' => 'Harem',
            'High Stakes Game' => 'Trò chơi mạo hiểm',
            'Historical' => 'Lịch sử',
            'Idols (Female)' => 'Thần tượng (Nữ)',
            'Idols (Male)' => 'Thần tượng (Nam)',
            'Isekai' => 'Isekai',
            'Iyashikei' => 'Iyashikei',
            'Love Polygon' => 'Tình yêu đa giác',
            'Magical Sex Shift' => 'Chuyển đổi giới tính',
            'Mahou Shoujo' => 'Mahou Shoujo',
            'Martial Arts' => 'Võ thuật',
            'Mecha' => 'Robot',
            'Medical' => 'Y khoa',
            'Military' => 'Quân sự',
            'Music' => 'Âm nhạc',
            'Mythology' => 'Thần thoại',
            'Organized Crime' => 'Tội phạm có tổ chức',
            'Otaku Culture' => 'Văn hóa Otaku',
            'Parody' => 'Parody',
            'Performing Arts' => 'Nghệ thuật biểu diễn',
            'Pets' => 'Thú cưng',
            'Psychological' => 'Tâm lý',
            'Racing' => 'Đua xe',
            'Reincarnation' => 'Đầu thai',
            'Reverse Harem' => 'Reverse Harem',
            'Love Status Quo' => 'Tình trạng tình yêu',
            'Samurai' => 'Samurai',
            'School' => 'Học đường',
            'Showbiz' => 'Giải trí',
            'Space' => 'Không gian',
            'Strategy Game' => 'Trò chơi chiến thuật',
            'Super Power' => 'Siêu năng lực',
            'Survival' => 'Sinh tồn',
            'Team Sports' => 'Thể thao đồng đội',
            'Time Travel' => 'Du hành thời gian',
            'Vampire' => 'Ma cà rồng',
            'Video Game' => 'Trò chơi điện tử',
            'Visual Arts' => 'Nghệ thuật thị giác',
            'Workplace' => 'Công sở',
            'Urban Fantasy' => 'Kỳ ảo đô thị',
            'Villainess' => 'Nữ phản diện',
            'Josei' => 'Josei',
            'Kids' => 'Thiếu nhi',
            'Seinen' => 'Seinen',
            'Shoujo' => 'Shoujo',
            'Shounen' => 'Shounen',
            'Other' => 'Khác'
        ];

        foreach ($genres as $genre) {
            $nameVn = $vietnameseTranslations[$genre['name']] ?? $genre['name'];
            \App\Models\Genres::where('id', $genre['id'])
                ->update(['name_vn' => $nameVn]);
        }
    }
}
